name: pocket_pcr_studio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  permission_handler: ^11.3.0
  marquee: ^2.2.3
  http: ^1.1.0
  xml: ^6.3.0
  flutter_screen_recording: ^2.1.0
  path_provider: ^2.0.15
  flutter_vlc_player: ^7.3.0
  geolocator: ^13.0.0

flutter:
  uses-material-design: true

