name: pocket_pcr_studio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  permission_handler: ^11.3.0
  marquee: ^2.2.3
  http: ^1.2.0
  xml: ^6.5.0
  flutter_vlc_player: ^7.4.1
  youtube_player_flutter: ^9.0.2
  qr_flutter: ^4.1.0
  path_provider: ^2.0.15
  geolocator: ^13.0.0


dependency_overrides:
  flutter_inappwebview_android: ^1.1.0

flutter:
  uses-material-design: true
