name: pocket_pcr_studio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  flutter_screen_recording: ^3.0.1

flutter:
  uses-material-design: true

