cmake_minimum_required(VERSION 3.10)

project(host_trace LANGUAGES C)

message(STATUS "TRACE_CMAKE_HOST_SYSTEM_NAME=${CMAKE_HOST_SYSTEM_NAME}")
message(STATUS "TRACE_CMAKE_HOST_SYSTEM_PROCESSOR=${CMAKE_HOST_SYSTEM_PROCESSOR}")
message(STATUS "TRACE_CMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}")
message(STATUS "TRACE_CMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}")
message(STATUS "TRACE_ANDROID_HOST_TAG=${ANDROID_HOST_TAG}")
message(STATUS "TRACE_CMAKE_ANDROID_NDK=${CMAKE_ANDROID_NDK}")
message(STATUS "TRACE_ANDROID_NDK=${ANDROID_NDK}")
message(STATUS "TRACE_CMAKE_C_COMPILER=${CMAKE_C_COMPILER}")
message(STATUS "TRACE_CMAKE_C_COMPILER_TARGET=${CMAKE_C_COMPILER_TARGET}")

add_library(test SHARED test.c)
