#!/data/data/com.termux/files/usr/bin/bash
exec "/data/data/com.termux/files/usr/bin/glibc-runner" "/data/data/com.termux/files/usr/glibc/bin/box64" "/data/data/com.termux/files/usr/opt/android-sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "$@"
